name: neuro_op
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - matplotlib
  - numpy
  - pymc[version='>=5']
  - scipy
  - seaborn
  - pandas
  - pip
  - pip:
    - networkx[default]
    - jax[cpu]
    - palettable
